const doctorsData = [
  {
    name: "Dr. Arjun Mehta",
    specialization: "Kidney Specialist",
    languages: ["Hindi", "English", "Telugu"],
    hospital: "Apollo Hospitals",
    location: "Hyderabad",
    price: 499,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    name: "Dr. Sara Thomas",
    specialization: "Cardiologist",
    languages: ["English", "Malayalam"],
    hospital: "Fortis Heart Institute",
    location: "Bengaluru",
    price: 599,
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    name: "Dr. Vivek Rana",
    specialization: "Neurologist",
    languages: ["English", "Hindi"],
    hospital: "AIIMS Delhi",
    location: "New Delhi",
    price: 799,
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Dr. Priya Desai",
    specialization: "Dermatologist",
    languages: ["English", "Gujarati"],
    hospital: "Kaya Skin Clinic",
    location: "Ahmedabad",
    price: 499,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    name: "Dr. Rajeev Menon",
    specialization: "Psychiatrist",
    languages: ["English", "Malayalam"],
    hospital: "NIMHANS",
    location: "Bengaluru",
    price: 649,
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Dr. Ayesha Qureshi",
    specialization: "Kidney Specialist",
    languages: ["English", "Urdu"],
    hospital: "Yashoda Hospitals",
    location: "Hyderabad",
    price: 550,
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    name: "Dr. Mohan Iyer",
    specialization: "Cardiologist",
    languages: ["English", "Hindi", "Kannada"],
    hospital: "Manipal Hospitals",
    location: "Bengaluru",
    price: 600,
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    name: "Dr. Sneha Patil",
    specialization: "Neurologist",
    languages: ["English", "Marathi"],
    hospital: "Sahyadri Hospital",
    location: "Pune",
    price: 700,
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    name: "Dr. Rakesh Nair",
    specialization: "Cardiologist",
    languages: ["English", "Hindi"],
    hospital: "Lilavati Hospital",
    location: "Mumbai",
    price: 699,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    name: "Dr. Meera Joshi",
    specialization: "Dermatologist",
    languages: ["English", "Hindi"],
    hospital: "DermaGlow Clinic",
    location: "Delhi",
    price: 450,
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    name: "Dr. Ankit Verma",
    specialization: "Psychiatrist",
    languages: ["English", "Hindi"],
    hospital: "MindSpace Wellness",
    location: "Lucknow",
    price: 480,
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    name: "Dr. Fatima Hussain",
    specialization: "Kidney Specialist",
    languages: ["English", "Urdu"],
    hospital: "Aster Hospital",
    location: "Kochi",
    price: 520,
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    name: "Dr. Gautam Shetty",
    specialization: "Cardiologist",
    languages: ["English", "Kannada"],
    hospital: "Fortis Hospitals",
    location: "Mysore",
    price: 599,
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Dr. Pooja Rani",
    specialization: "Neurologist",
    languages: ["English", "Punjabi"],
    hospital: "PGIMER",
    location: "Chandigarh",
    price: 790,
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    name: "Dr. Akshay Kulkarni",
    specialization: "Psychiatrist",
    languages: ["English", "Marathi"],
    hospital: "MindCare",
    location: "Nagpur",
    price: 470,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    name: "Dr. Ritu Aggarwal",
    specialization: "Dermatologist",
    languages: ["English", "Hindi"],
    hospital: "Apollo Clinic",
    location: "Jaipur",
    price: 500,
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    name: "Dr. Hemanth Reddy",
    specialization: "Kidney Specialist",
    languages: ["English", "Telugu"],
    hospital: "Sunshine Hospitals",
    location: "Hyderabad",
    price: 560,
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Dr. Kavita Sharma",
    specialization: "Cardiologist",
    languages: ["English", "Hindi"],
    hospital: "Max Hospitals",
    location: "Delhi",
    price: 640,
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    name: "Dr. Rohit Singh",
    specialization: "Neurologist",
    languages: ["English", "Hindi"],
    hospital: "Medanta Hospital",
    location: "Gurugram",
    price: 810,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    name: "Dr. Lakshmi Narayan",
    specialization: "Psychiatrist",
    languages: ["English", "Tamil"],
    hospital: "Apollo Hospitals",
    location: "Chennai",
    price: 480,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    name: "Dr. Tejas Shah",
    specialization: "Dermatologist",
    languages: ["English", "Gujarati"],
    hospital: "SkinSpace",
    location: "Surat",
    price: 550,
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    name: "Dr. Ananya Das",
    specialization: "Kidney Specialist",
    languages: ["English", "Bengali"],
    hospital: "Columbia Asia",
    location: "Kolkata",
    price: 530,
    image: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    name: "Dr. Amit Pathak",
    specialization: "Cardiologist",
    languages: ["English", "Hindi"],
    hospital: "Global Hospitals",
    location: "Indore",
    price: 610,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    name: "Dr. Roshni Prasad",
    specialization: "Neurologist",
    languages: ["English", "Tamil", "Hindi"],
    hospital: "SRM Hospital",
    location: "Chennai",
    price: 850,
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
];

export default doctorsData;
